import type { Move } from '../types/index.js';

export const MOVES: Record<string, Move> = {
  tackle: { id: 'tackle', name: '撞击', type: 'Normal', category: 'Physical', power: 40, accuracy: 100, ppMax: 35, description: '用整个身体 撞向对手进行攻击。' },
  growl: { id: 'growl', name: '叫声', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 40, description: '让对手听可爱的叫声， 引开注意力使其疏忽， 从而降低对手的攻击。' },
  leechSeed: { id: 'leechSeed', name: '寄生种子', type: 'Grass', category: 'Status', power: 0, accuracy: 90, ppMax: 10, description: '植入寄生种子后，将在每回合 一点一点吸取对手的ＨＰ， 从而用来回复自己的ＨＰ。' },
  vineWhip: { id: 'vineWhip', name: '藤鞭', type: 'Grass', category: 'Physical', power: 45, accuracy: 100, ppMax: 25, description: '用如同鞭子般弯曲而细长的藤蔓 摔打对手进行攻击。' },
  scratch: { id: 'scratch', name: '抓', type: 'Normal', category: 'Physical', power: 40, accuracy: 100, ppMax: 35, description: '用坚硬且无比锋利的爪子 抓对手进行攻击。' },
  ember: { id: 'ember', name: '火花', type: 'Fire', category: 'Special', power: 40, accuracy: 100, ppMax: 25, description: '向对手发射 小型火焰进行攻击。 有时会让对手陷入灼伤状态。' },
  metalClaw: { id: 'metalClaw', name: '金属爪', type: 'Steel', category: 'Physical', power: 50, accuracy: 95, ppMax: 35, description: '用钢铁之爪 劈开对手进行攻击。 有时会提高自己的攻击。' },
  leer: { id: 'leer', name: '瞪眼', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '用犀利的眼神使其害怕， 从而降低对手的防御。' },
  tailWhip: { id: 'tailWhip', name: '摇尾巴', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '可爱地左右摇晃尾巴， 诱使对手疏忽大意。 会降低对手的防御。' },
  bubble: { id: 'bubble', name: '泡沫', type: 'Water', category: 'Special', power: 40, accuracy: 100, ppMax: 30, description: '向对手用力吹起无数泡泡进行攻击。 有时会降低对手的速度。' },
  waterGun: { id: 'waterGun', name: '水枪', type: 'Water', category: 'Special', power: 40, accuracy: 100, ppMax: 25, description: '向对手猛烈地喷射 水流进行攻击。' },
  stringShot: { id: 'stringShot', name: '吐丝', type: 'Bug', category: 'Status', power: 0, accuracy: 95, ppMax: 40, description: '用口中吐出的丝缠绕对手， 从而大幅降低对手的速度。' },
  harden: { id: 'harden', name: '变硬', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '全身使劲，让身体变硬， 从而提高自己的防御。' },
  confusion: { id: 'confusion', name: '念力', type: 'Psychic', category: 'Special', power: 50, accuracy: 100, ppMax: 25, description: '向对手发送 微弱的念力进行攻击。 有时会使对手混乱。' },
  poisonPowder: { id: 'poisonPowder', name: '毒粉', type: 'Poison', category: 'Status', power: 0, accuracy: 75, ppMax: 35, description: '撒出毒粉， 从而让对手陷入中毒状态。' },
  stunSpore: { id: 'stunSpore', name: '麻痹粉', type: 'Grass', category: 'Status', power: 0, accuracy: 75, ppMax: 30, description: '撒出麻痹粉， 从而让对手陷入麻痹状态。' },
  sleepPowder: { id: 'sleepPowder', name: '催眠粉', type: 'Grass', category: 'Status', power: 0, accuracy: 75, ppMax: 15, description: '撒出催眠粉， 从而让对手陷入睡眠状态。' },
  poisonSting: { id: 'poisonSting', name: '毒针', type: 'Poison', category: 'Physical', power: 15, accuracy: 100, ppMax: 35, description: '将有毒的针 刺入对手进行攻击。 有时会让对手陷入中毒状态。' },
  furyAttack: { id: 'furyAttack', name: '乱击', type: 'Normal', category: 'Physical', power: 15, accuracy: 85, ppMax: 20, description: '用角或喙 刺向对手进行攻击。 连续攻击２～５次。' },
  focusEnergy: { id: 'focusEnergy', name: '聚气', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '深深地吸口气，集中精神。 自己的攻击 会变得容易击中要害。' },
  twineedle: { id: 'twineedle', name: '双针', type: 'Bug', category: 'Physical', power: 25, accuracy: 100, ppMax: 20, description: '将２根针刺入对手， 连续２次给予伤害。 有时会让对手陷入中毒状态。' },
  rage: { id: 'rage', name: '愤怒', type: 'Normal', category: 'Physical', power: 20, accuracy: 100, ppMax: 20, description: '如果在使出招式后 受到攻击的话， 会因愤怒的力量而提高攻击。' },
  gust: { id: 'gust', name: '起风', type: 'Flying', category: 'Special', power: 40, accuracy: 100, ppMax: 35, description: '用翅膀将刮起的狂风 袭向对手进行攻击。' },
  sandAttack: { id: 'sandAttack', name: '泼沙', type: 'Ground', category: 'Status', power: 0, accuracy: 100, ppMax: 15, description: '向对手脸上泼沙子， 从而降低命中率。' },
  quickAttack: { id: 'quickAttack', name: '电光一闪', type: 'Normal', category: 'Physical', power: 40, accuracy: 100, ppMax: 30, description: '以迅雷不及掩耳之势扑向对手。 必定能够先制攻击。' },
  hyperFang: { id: 'hyperFang', name: '必杀门牙', type: 'Normal', category: 'Physical', power: 80, accuracy: 90, ppMax: 15, description: '用锋利的门牙 牢牢地咬住对手进行攻击。 有时会使对手畏缩。' },
  peck: { id: 'peck', name: '啄', type: 'Flying', category: 'Physical', power: 35, accuracy: 100, ppMax: 35, description: '用尖锐的喙或角 刺向对手进行攻击。' },
  wrap: { id: 'wrap', name: '紧束', type: 'Normal', category: 'Physical', power: 15, accuracy: 90, ppMax: 20, description: '使用长长的身体或藤蔓等， 在４～５回合内 紧束对手进行攻击。' },
  bite: { id: 'bite', name: '咬住', type: 'Dark', category: 'Physical', power: 60, accuracy: 100, ppMax: 25, description: '用尖锐的牙 咬住对手进行攻击。 有时会使对手畏缩。' },
  thunderShock: { id: 'thunderShock', name: '电击', type: 'Electric', category: 'Special', power: 40, accuracy: 100, ppMax: 30, description: '发出电流刺激对手进行攻击。 有时会让对手陷入麻痹状态。' },
  thunderWave: { id: 'thunderWave', name: '电磁波', type: 'Electric', category: 'Status', power: 0, accuracy: 90, ppMax: 20, description: '向对手发出 微弱的电击， 从而让对手陷入麻痹状态。' },
  thunderbolt: { id: 'thunderbolt', name: '十万伏特', type: 'Electric', category: 'Special', power: 90, accuracy: 100, ppMax: 15, description: '向对手发出 强力电击进行攻击。 有时会让对手陷入麻痹状态。' },
  defenseCurl: { id: 'defenseCurl', name: '变圆', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 40, description: '将身体蜷曲变圆， 从而提高自己的防御。' },
  slash: { id: 'slash', name: '劈开', type: 'Normal', category: 'Physical', power: 70, accuracy: 100, ppMax: 20, description: '用爪子或镰刀等 劈开对手进行攻击。 容易击中要害。' },
  bodySlam: { id: 'bodySlam', name: '泰山压顶', type: 'Normal', category: 'Physical', power: 85, accuracy: 100, ppMax: 15, description: '用整个身体 压住对手进行攻击。 有时会让对手陷入麻痹状态。' },
  hornAttack: { id: 'hornAttack', name: '角撞', type: 'Normal', category: 'Physical', power: 65, accuracy: 100, ppMax: 25, description: '用尖锐的角攻击对手。' },
  thrash: { id: 'thrash', name: '大闹一番', type: 'Normal', category: 'Physical', power: 120, accuracy: 100, ppMax: 10, description: '在２～３回合内， 乱打一气地攻击对手。 大闹一番后自己会陷入混乱。' },
  pound: { id: 'pound', name: '拍击', type: 'Normal', category: 'Physical', power: 40, accuracy: 100, ppMax: 35, description: '使用长长的尾巴或手等 拍打对手进行攻击。' },
  encore: { id: 'encore', name: '再来一次', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 5, description: '让对手接受再来一次， 连续３次使出最后使用的招式。' },
  sing: { id: 'sing', name: '唱歌', type: 'Normal', category: 'Status', power: 0, accuracy: 55, ppMax: 15, description: '让对手听舒适、 美妙的歌声， 从而陷入睡眠状态。' },
  doubleSlap: { id: 'doubleSlap', name: '连环巴掌', type: 'Normal', category: 'Physical', power: 15, accuracy: 85, ppMax: 10, description: '用连环巴掌 拍打对手进行攻击。 连续攻击２～５次。' },
  minimize: { id: 'minimize', name: '变小', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '蜷缩身体显得很小， 从而大幅提高 自己的闪避率。' },
  metronome: { id: 'metronome', name: '挥指', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '挥动手指刺激自己的大脑， 从所有的招式中 任意使出１个。' },
  willOWisp: { id: 'willOWisp', name: '鬼火', type: 'Fire', category: 'Status', power: 0, accuracy: 85, ppMax: 15, description: '放出怪异的火焰， 从而让对手陷入灼伤状态。' },
  roar: { id: 'roar', name: '吼叫', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '放走对手，强制拉后备宝可梦上场。 如果对手为野生宝可梦， 战斗将直接结束。' },
  disable: { id: 'disable', name: '定身法', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '阻碍对手行动， 之前使出的招式 将在４回合内无法使用。' },
  leechLife: { id: 'leechLife', name: '吸血', type: 'Bug', category: 'Physical', power: 80, accuracy: 100, ppMax: 10, description: '吸取血液攻击对手。 可以回复给予对手 伤害的一半ＨＰ。' },
  astonish: { id: 'astonish', name: '惊吓', type: 'Ghost', category: 'Physical', power: 30, accuracy: 100, ppMax: 15, description: '用尖叫声等 突然惊吓对手进行攻击。 有时会使对手畏缩。' },
  supersonic: { id: 'supersonic', name: '超音波', type: 'Normal', category: 'Status', power: 0, accuracy: 55, ppMax: 20, description: '从身体发出 特殊的音波， 从而使对手混乱。' },
  screech: { id: 'screech', name: '刺耳声', type: 'Normal', category: 'Status', power: 0, accuracy: 85, ppMax: 40, description: '发出不由自主想要 捂起耳朵的刺耳声， 从而大幅降低对手的防御。' },
  absorb: { id: 'absorb', name: '吸取', type: 'Grass', category: 'Special', power: 20, accuracy: 100, ppMax: 25, description: '吸取对手的养分进行攻击。 可以回复给予对手 伤害的一半ＨＰ。' },
  sweetScent: { id: 'sweetScent', name: '甜甜香气', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '用香气大幅降低对手的闪避率。' },
  acid: { id: 'acid', name: '溶解液', type: 'Poison', category: 'Special', power: 40, accuracy: 100, ppMax: 30, description: '将强酸泼向对手进行攻击。 有时会降低对手的特防。' },
  megaDrain: { id: 'megaDrain', name: '超级吸取', type: 'Grass', category: 'Special', power: 40, accuracy: 100, ppMax: 15, description: '吸取对手的养分进行攻击。 可以回复给予对手 伤害的一半ＨＰ。' },
  foresight: { id: 'foresight', name: '识破', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 40, description: '对幽灵属性宝可梦没有效果的招式 以及闪避率高的对手， 使用后变得能够打中。' },
  magnitude: { id: 'magnitude', name: '震级', type: 'Ground', category: 'Physical', power: 0, accuracy: 100, ppMax: 30, description: '晃动地面，攻击自己 周围所有的宝可梦。 招式的威力会有各种变化。' },
  dig: { id: 'dig', name: '挖洞', type: 'Ground', category: 'Physical', power: 80, accuracy: 100, ppMax: 10, description: '第１回合钻入， 第２回合攻击对手。' },
  triAttack: { id: 'triAttack', name: '三重攻击', type: 'Normal', category: 'Special', power: 80, accuracy: 100, ppMax: 10, description: '用３种光线进行攻击。 有时会让对手陷入 麻痹、灼伤或冰冻的状态。' },
  payDay: { id: 'payDay', name: '聚宝功', type: 'Normal', category: 'Physical', power: 40, accuracy: 100, ppMax: 20, description: '向对手的身体 投掷小金币进行攻击。 战斗后可以拿到钱。' },
  waterSport: { id: 'waterSport', name: '玩水', type: 'Water', category: 'Status', power: 0, accuracy: 100, ppMax: 15, description: '用水湿透周围。 在５回合内 减弱火属性的招式。' },
  lowKick: { id: 'lowKick', name: '踢倒', type: 'Fighting', category: 'Physical', power: 0, accuracy: 100, ppMax: 20, description: '用力踢对手的脚， 使其摔倒进行攻击。 对手越重，威力越大。' },
  karateChop: { id: 'karateChop', name: '空手劈', type: 'Fighting', category: 'Physical', power: 50, accuracy: 100, ppMax: 25, description: '用锋利的手刀 劈向对手进行攻击。 容易击中要害。' },
  odorSleuth: { id: 'odorSleuth', name: '气味侦测', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 40, description: '对幽灵属性宝可梦没有效果的招式 以及闪避率高的对手， 使用后变得能够打中。' },
  takeDown: { id: 'takeDown', name: '猛撞', type: 'Normal', category: 'Physical', power: 90, accuracy: 85, ppMax: 20, description: '以惊人的气势 撞向对手进行攻击。 自己也会受到少许伤害。' },
  hypnosis: { id: 'hypnosis', name: '催眠术', type: 'Psychic', category: 'Status', power: 0, accuracy: 60, ppMax: 20, description: '施以诱导睡意的暗示， 让对手陷入睡眠状态。' },
  submission: { id: 'submission', name: '地狱翻滚', type: 'Fighting', category: 'Physical', power: 80, accuracy: 80, ppMax: 20, description: '将对手连同自己一起 摔向地面进行攻击。 自己也会受到少许伤害。' },
  teleport: { id: 'teleport', name: '瞬间移动', type: 'Psychic', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '停止和野生宝可梦战斗并逃走。' },
  kinesis: { id: 'kinesis', name: '折弯汤匙', type: 'Psychic', category: 'Status', power: 0, accuracy: 80, ppMax: 15, description: '折弯汤匙引开注意， 从而降低对手的命中率。' },
  growth: { id: 'growth', name: '生长', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '让身体一下子长大， 从而提高攻击和特攻。' },
  razorLeaf: { id: 'razorLeaf', name: '飞叶快刀', type: 'Grass', category: 'Physical', power: 55, accuracy: 95, ppMax: 25, description: '飞出叶片， 切斩对手进行攻击。 容易击中要害。' },
  mudSport: { id: 'mudSport', name: '玩泥巴', type: 'Ground', category: 'Status', power: 0, accuracy: 100, ppMax: 15, description: '一旦使用此招式， 周围就会弄得到处是泥。 在５回合内减弱电属性的招式。' },
  rockThrow: { id: 'rockThrow', name: '落石', type: 'Rock', category: 'Physical', power: 50, accuracy: 90, ppMax: 15, description: '拿起小岩石， 投掷对手进行攻击。' },
  stomp: { id: 'stomp', name: '踩踏', type: 'Normal', category: 'Physical', power: 65, accuracy: 100, ppMax: 20, description: '用大脚踩踏对手进行攻击。 有时会使对手畏缩。' },
  curse: { id: 'curse', name: '诅咒', type: 'Ghost', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '使用该招式的宝可梦， 其属性是幽灵属性或其他属性时， 效果会不一样。' },
  yawn: { id: 'yawn', name: '哈欠', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '打个大哈欠引起睡意。 在下一回合让对手陷入睡眠状态。' },
  headbutt: { id: 'headbutt', name: '头锤', type: 'Normal', category: 'Physical', power: 70, accuracy: 100, ppMax: 15, description: '将头伸出， 笔直地扑向对手进行攻击。 有时会使对手畏缩。' },
  metalSound: { id: 'metalSound', name: '金属音', type: 'Steel', category: 'Status', power: 0, accuracy: 85, ppMax: 40, description: '让对手听摩擦金属般 讨厌的声音。 大幅降低对手的特防。' },
  sonicBoom: { id: 'sonicBoom', name: '音爆', type: 'Normal', category: 'Special', power: 0, accuracy: 90, ppMax: 20, description: '将冲击波 撞向对手进行攻击。 必定会给予２０的伤害。' },
  pursuit: { id: 'pursuit', name: '追打', type: 'Dark', category: 'Physical', power: 40, accuracy: 100, ppMax: 20, description: '当对手替换宝可梦上场时 使出此招式的话， 能够以２倍的威力进行攻击。' },
  icyWind: { id: 'icyWind', name: '冰冻之风', type: 'Ice', category: 'Special', power: 55, accuracy: 95, ppMax: 15, description: '将结冰的冷气 吹向对手进行攻击。 会降低对手的速度。' },
  auroraBeam: { id: 'auroraBeam', name: '极光束', type: 'Ice', category: 'Special', power: 65, accuracy: 100, ppMax: 20, description: '向对手发射 虹色光束进行攻击。 有时会降低对手的攻击。' },
  poisonGas: { id: 'poisonGas', name: '毒瓦斯', type: 'Poison', category: 'Status', power: 0, accuracy: 90, ppMax: 40, description: '将毒瓦斯吹到对手的脸上， 从而让对手陷入中毒状态。' },
  withdraw: { id: 'withdraw', name: '缩入壳中', type: 'Water', category: 'Status', power: 0, accuracy: 100, ppMax: 40, description: '缩入壳里保护身体， 从而提高自己的防御。' },
  icicleSpear: { id: 'icicleSpear', name: '冰锥', type: 'Ice', category: 'Physical', power: 25, accuracy: 100, ppMax: 30, description: '向对手发射 锋利的冰柱进行攻击。 连续攻击２～５次。' },
  clamp: { id: 'clamp', name: '贝壳夹击', type: 'Water', category: 'Physical', power: 35, accuracy: 85, ppMax: 15, description: '用非常坚固且厚实的贝壳， 在４～５回合内 夹住对手进行攻击。' },
  nightShade: { id: 'nightShade', name: '黑夜魔影', type: 'Ghost', category: 'Special', power: 0, accuracy: 100, ppMax: 15, description: '显示恐怖幻影， 只给予对手 和自己等级相同的伤害。' },
  confuseRay: { id: 'confuseRay', name: '奇异之光', type: 'Ghost', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '显示奇怪的光， 扰乱对手。 使对手混乱。' },
  lick: { id: 'lick', name: '舌舔', type: 'Ghost', category: 'Physical', power: 30, accuracy: 100, ppMax: 30, description: '用长长的舌头， 舔遍对手进行攻击。 有时会让对手陷入麻痹状态。' },
  spite: { id: 'spite', name: '怨恨', type: 'Ghost', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '对对手最后使用的招式 怀有怨恨， 减少４ＰＰ该招式。' },
  bind: { id: 'bind', name: '绑紧', type: 'Normal', category: 'Physical', power: 15, accuracy: 85, ppMax: 20, description: '使用长长的身体或藤蔓等， 在４～５回合内 绑紧对手进行攻击。' },
  viceGrip: { id: 'viceGrip', name: '夹住', type: 'Normal', category: 'Physical', power: 55, accuracy: 100, ppMax: 30, description: '将对手从两侧夹住， 给予伤害。' },
  mudShot: { id: 'mudShot', name: '泥巴射击', type: 'Ground', category: 'Special', power: 55, accuracy: 95, ppMax: 15, description: '向对手投掷 泥块进行攻击。 同时降低对手的速度。' },
  charge: { id: 'charge', name: '充电', type: 'Electric', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '提高下一回合使出的 电属性的招式威力。 自己的特防也会提高。' },
  barrage: { id: 'barrage', name: '投球', type: 'Normal', category: 'Physical', power: 15, accuracy: 85, ppMax: 20, description: '向对手投掷 圆形物体进行攻击。 连续攻击２～５次。' },
  uproar: { id: 'uproar', name: '吵闹', type: 'Normal', category: 'Special', power: 90, accuracy: 100, ppMax: 10, description: '在３回合内 用骚乱攻击对手。 在此期间谁都不能入眠。' },
  boneClub: { id: 'boneClub', name: '骨棒', type: 'Ground', category: 'Physical', power: 65, accuracy: 85, ppMax: 20, description: '用手中的骨头 殴打对手进行攻击。 有时会使对手畏缩。' },
  doubleKick: { id: 'doubleKick', name: '二连踢', type: 'Fighting', category: 'Physical', power: 30, accuracy: 100, ppMax: 30, description: '用２只脚踢飞对手进行攻击。 连续２次给予伤害。' },
  meditate: { id: 'meditate', name: '瑜伽姿势', type: 'Psychic', category: 'Status', power: 0, accuracy: 100, ppMax: 40, description: '唤醒身体深处 沉睡的力量， 从而提高自己的攻击。' },
  revenge: { id: 'revenge', name: '报复', type: 'Fighting', category: 'Physical', power: 60, accuracy: 100, ppMax: 10, description: '如果受到对手的招式攻击， 就能给予对手２倍的伤害。' },
  brickBreak: { id: 'brickBreak', name: '劈瓦', type: 'Fighting', category: 'Physical', power: 75, accuracy: 100, ppMax: 15, description: '将手刀猛烈地挥下攻击对手。 还可以破坏光墙和反射壁等。' },
  cometPunch: { id: 'cometPunch', name: '连续拳', type: 'Normal', category: 'Physical', power: 18, accuracy: 85, ppMax: 15, description: '用拳头怒涛般的 殴打对手进行攻击。 连续攻击２～５次。' },
  agility: { id: 'agility', name: '高速移动', type: 'Psychic', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '让身体放松变得轻盈， 以便高速移动。 大幅提高自己的速度。' },
  smog: { id: 'smog', name: '浊雾', type: 'Poison', category: 'Special', power: 30, accuracy: 70, ppMax: 20, description: '将肮脏的浓雾 吹向对手进行攻击。 有时会让对手陷入中毒状态。' },
  sludge: { id: 'sludge', name: '污泥攻击', type: 'Poison', category: 'Special', power: 65, accuracy: 100, ppMax: 20, description: '用污泥投掷对手进行攻击。 有时会让对手陷入中毒状态。' },
  scaryFace: { id: 'scaryFace', name: '鬼面', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '用恐怖的脸瞪着对手， 使其害怕， 从而大幅降低对手的速度。' },
  rockBlast: { id: 'rockBlast', name: '岩石爆击', type: 'Rock', category: 'Physical', power: 25, accuracy: 90, ppMax: 10, description: '向对手发射 坚硬的岩石进行攻击。 连续攻击２～５次。' },
  refresh: { id: 'refresh', name: '焕然一新', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '让身体休息， 治愈自己身上所中的 毒、麻痹、灼伤的异常状态。' },
  constrict: { id: 'constrict', name: '缠绕', type: 'Normal', category: 'Physical', power: 10, accuracy: 100, ppMax: 35, description: '用触手或青藤等缠绕进行攻击。 有时会降低对手的速度。' },
  ingrain: { id: 'ingrain', name: '扎根', type: 'Grass', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '在大地上扎根， 每回合回复自己的ＨＰ。 因为扎根了，所以不能替换宝可梦。' },
  fakeOut: { id: 'fakeOut', name: '击掌奇袭', type: 'Normal', category: 'Physical', power: 40, accuracy: 100, ppMax: 10, description: '进行先制攻击，使对手畏缩。 要在出场后立刻使出才能成功。' },
  smokescreen: { id: 'smokescreen', name: '烟幕', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '向对手喷出烟或墨汁等， 从而降低对手的命中率。' },
  twister: { id: 'twister', name: '龙卷风', type: 'Dragon', category: 'Special', power: 40, accuracy: 100, ppMax: 20, description: '兴起龙卷风， 将对手卷入进行攻击。 有时会使对手畏缩。' },
  rapidSpin: { id: 'rapidSpin', name: '高速旋转', type: 'Normal', category: 'Physical', power: 50, accuracy: 100, ppMax: 40, description: '通过旋转来攻击对手。 还可以摆脱绑紧、紧束、 寄生种子和撒菱等招式。' },
  camouflage: { id: 'camouflage', name: '保护色', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '根据所在场所不同， 如水边、草丛和洞窟等， 可以改变自己的属性。' },
  recover: { id: 'recover', name: '自我再生', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 5, description: '让细胞再生， 从而回复自己 最大ＨＰ的一半。' },
  barrier: { id: 'barrier', name: '屏障', type: 'Psychic', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '制造坚固的壁障， 从而大幅提高自己的防御。' },
  reflect: { id: 'reflect', name: '反射壁', type: 'Psychic', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '在５回合内使用神奇的墙， 减弱从对手那受到的 物理攻击的伤害。' },
  magicalLeaf: { id: 'magicalLeaf', name: '魔法叶', type: 'Grass', category: 'Special', power: 60, accuracy: 100, ppMax: 20, description: '散落可以追踪 对手的神奇叶片。 攻击必定会命中。' },
  falseSwipe: { id: 'falseSwipe', name: '点到为止', type: 'Normal', category: 'Physical', power: 40, accuracy: 100, ppMax: 40, description: '对手的ＨＰ 至少会留下１ＨＰ， 如此般手下留情地攻击。' },
  lovelyKiss: { id: 'lovelyKiss', name: '恶魔之吻', type: 'Normal', category: 'Status', power: 0, accuracy: 75, ppMax: 10, description: '用恐怖的脸强吻对手。 让对手陷入睡眠状态。' },
  powderSnow: { id: 'powderSnow', name: '细雪', type: 'Ice', category: 'Special', power: 40, accuracy: 100, ppMax: 25, description: '将冰冷的细雪 吹向对手进行攻击。 有时会让对手陷入冰冻状态。' },
  swift: { id: 'swift', name: '高速星星', type: 'Normal', category: 'Special', power: 60, accuracy: 100, ppMax: 20, description: '发射星形的光攻击对手。 攻击必定会命中。' },
  sunnyDay: { id: 'sunnyDay', name: '大晴天', type: 'Fire', category: 'Status', power: 0, accuracy: 100, ppMax: 5, description: '在５回合内阳光变得强烈， 从而提高火属性的招式威力。 水属性的招式威力则降低。' },
  rainDance: { id: 'rainDance', name: '求雨', type: 'Water', category: 'Status', power: 0, accuracy: 100, ppMax: 5, description: '在５回合内一直降雨， 从而提高水属性的招式威力。 火属性的招式威力则降低。' },
  sandstorm: { id: 'sandstorm', name: '沙暴', type: 'Rock', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '在５回合内扬起沙暴， 除岩石、地面和钢属性以外的宝可梦， 都会受到伤害。' },
  hail: { id: 'hail', name: '冰雹', type: 'Ice', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '在５回合内降下冰雹， 除冰属性以外的宝可梦， 都会受到伤害。' },
  seismicToss: { id: 'seismicToss', name: '地球上投', type: 'Fighting', category: 'Physical', power: 0, accuracy: 100, ppMax: 20, description: '利用引力将对手甩飞出去。 给予对手和自己等级相同的伤害。' },
  splash: { id: 'splash', name: '跃起', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 40, description: '也不攻击只是一蹦一蹦地跳， 什么都不会发生……' },
  flail: { id: 'flail', name: '抓狂', type: 'Normal', category: 'Physical', power: 0, accuracy: 100, ppMax: 15, description: '抓狂般乱打进行攻击。 自己的ＨＰ越少， 招式的威力越大。' },
  mist: { id: 'mist', name: '白雾', type: 'Ice', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '用白雾覆盖身体。 在５回合内不会让对手 降低自己的能力。' },
  transform: { id: 'transform', name: '变身', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 10, description: '变身成对手宝可梦的样子， 能够使用和对手 完全相同的招式。' },
  helpingHand: { id: 'helpingHand', name: '帮助', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '帮助伙伴。 被帮助的宝可梦， 其招式威力变得比平时大。' },
  sharpen: { id: 'sharpen', name: '棱角化', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '增加身体的角， 变得棱棱角角， 从而提高自己的攻击。' },
  conversion: { id: 'conversion', name: '纹理', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '将自己的属性转换成 和已学会的招式中 第一个招式相同的属性。' },
  conversion2: { id: 'conversion2', name: '纹理２', type: 'Normal', category: 'Status', power: 0, accuracy: 100, ppMax: 30, description: '为了可以抵抗对手 最后使用的招式， 从而使自己的属性发生变化。' },
  furyCutter: { id: 'furyCutter', name: '连斩', type: 'Bug', category: 'Physical', power: 40, accuracy: 95, ppMax: 20, description: '用镰刀或爪子等 切斩对手进行攻击。 连续击中，威力就会提高。' },
  wingAttack: { id: 'wingAttack', name: '翅膀攻击', type: 'Flying', category: 'Physical', power: 60, accuracy: 100, ppMax: 35, description: '大大地展开美丽的翅膀， 将其撞向对手进行攻击。' },
  ancientPower: { id: 'ancientPower', name: '原始之力', type: 'Rock', category: 'Special', power: 60, accuracy: 100, ppMax: 5, description: '用原始之力进行攻击。 有时会提高 自己所有的能力。' },
  amnesia: { id: 'amnesia', name: '瞬间失忆', type: 'Psychic', category: 'Status', power: 0, accuracy: 100, ppMax: 20, description: '将头脑清空， 瞬间忘记某事， 从而大幅提高自己的特防。' },
  rest: { id: 'rest', name: '睡觉', type: 'Psychic', category: 'Status', power: 0, accuracy: 100, ppMax: 5, description: '连续睡上２回合。 回复自己的全部ＨＰ 以及治愈所有异常状态。' },
  iceBeam: { id: 'iceBeam', name: '冰冻光束', type: 'Ice', category: 'Special', power: 90, accuracy: 100, ppMax: 10, description: '向对手发射 冰冻光束进行攻击。 有时会让对手陷入冰冻状态。' },
  drillPeck: { id: 'drillPeck', name: '啄钻', type: 'Flying', category: 'Physical', power: 80, accuracy: 100, ppMax: 20, description: '一边旋转，一边将尖喙 刺入对手进行攻击。' },
  fireSpin: { id: 'fireSpin', name: '火焰旋涡', type: 'Fire', category: 'Special', power: 35, accuracy: 85, ppMax: 15, description: '将对手困在 激烈的火焰旋涡中， 在４～５回合内进行攻击。' },
  psychic: { id: 'psychic', name: '精神强念', type: 'Psychic', category: 'Special', power: 90, accuracy: 100, ppMax: 10, description: '向对手发送 强大的念力进行攻击。 有时会降低对手的特防。' },
  megaPunch: { id: 'megaPunch', name: '百万吨重拳', type: 'Normal', category: 'Physical', power: 80, accuracy: 85, ppMax: 20, description: '用充满力量的拳头攻击对手。' },
};

export const MOVE_EFFECTS: Record<string, {
  type: 'status' | 'weather' | 'heal';
  id: string;
  chance: number;
  value?: number;
}> = {
    ember: { type: 'status', id: 'BRN', chance: 0.1 },
    flamethrower: { type: 'status', id: 'BRN', chance: 0.1 },
    fireBlast: { type: 'status', id: 'BRN', chance: 0.1 }, 
    willOWisp: { type: 'status', id: 'BRN', chance: 0.85 }, 
    poisonPowder: { type: 'status', id: 'PSN', chance: 1.0 },
    poisonSting: { type: 'status', id: 'PSN', chance: 0.3 },
    sludge: { type: 'status', id: 'PSN', chance: 0.3 },
    sleepPowder: { type: 'status', id: 'SLP', chance: 1.0 },
    hypnosis: { type: 'status', id: 'SLP', chance: 1.0 },
    sing: { type: 'status', id: 'SLP', chance: 1.0 },
    stunSpore: { type: 'status', id: 'PAR', chance: 1.0 },
    thunderWave: { type: 'status', id: 'PAR', chance: 1.0 },
    thunderShock: { type: 'status', id: 'PAR', chance: 0.1 },
    thunderbolt: { type: 'status', id: 'PAR', chance: 0.1 },
    bodySlam: { type: 'status', id: 'PAR', chance: 0.3 },
    lick: { type: 'status', id: 'PAR', chance: 0.3 },
    iceBeam: { type: 'status', id: 'FRZ', chance: 0.1 },
    powderSnow: { type: 'status', id: 'FRZ', chance: 0.1 },
    blizzard: { type: 'status', id: 'FRZ', chance: 0.1 },
    
    sunnyDay: { type: 'weather', id: 'Sunny', chance: 1.0 },
    rainDance: { type: 'weather', id: 'Rain', chance: 1.0 },
    sandstorm: { type: 'weather', id: 'Sandstorm', chance: 1.0 },
    hail: { type: 'weather', id: 'Hail', chance: 1.0 },
};
