import type { SpeciesData } from '../types';

export const SPECIES_DATA: Record<string, SpeciesData> = {
  bulbasaur: {
    pokedexId: 1,
    speciesName: '妙蛙种子',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 45, atk: 49, def: 49, spa: 65, spd: 65, spe: 45 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'leechSeed', level: 7 }, { moveId: 'vineWhip', level: 13 }],
    evolutions: [{ targetSpeciesId: 'ivysaur', level: 16 }],
  },
  ivysaur: {
    pokedexId: 2,
    speciesName: '妙蛙草',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 60, atk: 62, def: 63, spa: 80, spd: 80, spe: 60 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'leechSeed', level: 1 }, { moveId: 'vineWhip', level: 13 }],
    evolutions: [{ targetSpeciesId: 'venusaur', level: 32 }],
  },
  venusaur: {
    pokedexId: 3,
    speciesName: '妙蛙花',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 80, atk: 82, def: 83, spa: 100, spd: 100, spe: 80 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
    learnset: [{ moveId: 'vineWhip', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'leechSeed', level: 1 }],
  },
  charmander: {
    pokedexId: 4,
    speciesName: '小火龙',
    types: ['Fire'],
    baseStats: { hp: 39, atk: 52, def: 43, spa: 60, spd: 50, spe: 65 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'ember', level: 9 }, { moveId: 'metalClaw', level: 13 }],
    evolutions: [{ targetSpeciesId: 'charmeleon', level: 16 }],
  },
  charmeleon: {
    pokedexId: 5,
    speciesName: '火恐龙',
    types: ['Fire'],
    baseStats: { hp: 58, atk: 64, def: 58, spa: 80, spd: 65, spe: 80 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'ember', level: 1 }, { moveId: 'metalClaw', level: 13 }],
    evolutions: [{ targetSpeciesId: 'charizard', level: 36 }],
  },
  charizard: {
    pokedexId: 6,
    speciesName: '喷火龙',
    types: ['Fire', 'Flying'],
    baseStats: { hp: 78, atk: 84, def: 78, spa: 109, spd: 85, spe: 100 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'ember', level: 1 }],
  },
  squirtle: {
    pokedexId: 7,
    speciesName: '杰尼龟',
    types: ['Water'],
    baseStats: { hp: 44, atk: 48, def: 65, spa: 50, spd: 64, spe: 43 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'bubble', level: 8 }, { moveId: 'waterGun', level: 15 }],
    evolutions: [{ targetSpeciesId: 'wartortle', level: 16 }],
  },
  wartortle: {
    pokedexId: 8,
    speciesName: '卡咪龟',
    types: ['Water'],
    baseStats: { hp: 59, atk: 63, def: 80, spa: 65, spd: 80, spe: 58 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'bubble', level: 1 }, { moveId: 'waterGun', level: 15 }],
    evolutions: [{ targetSpeciesId: 'blastoise', level: 36 }],
  },
  blastoise: {
    pokedexId: 9,
    speciesName: '水箭龟',
    types: ['Water'],
    baseStats: { hp: 79, atk: 83, def: 100, spa: 85, spd: 105, spe: 78 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'waterGun', level: 1 }, { moveId: 'bubble', level: 1 }],
  },
  caterpie: {
    pokedexId: 10,
    speciesName: '绿毛虫',
    types: ['Bug'],
    baseStats: { hp: 45, atk: 30, def: 35, spa: 20, spd: 20, spe: 45 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'stringShot', level: 1 }],
    evolutions: [{ targetSpeciesId: 'metapod', level: 7 }],
  },
  metapod: {
    pokedexId: 11,
    speciesName: '铁甲蛹',
    types: ['Bug'],
    baseStats: { hp: 50, atk: 20, def: 55, spa: 25, spd: 25, spe: 30 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',
    learnset: [{ moveId: 'harden', level: 1 }],
    evolutions: [{ targetSpeciesId: 'butterfree', level: 10 }],
  },
  butterfree: {
    pokedexId: 12,
    speciesName: '巴大蝶',
    types: ['Bug', 'Flying'],
    baseStats: { hp: 60, atk: 45, def: 50, spa: 90, spd: 80, spe: 70 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',
    learnset: [{ moveId: 'confusion', level: 1 }, { moveId: 'poisonPowder', level: 15 }, { moveId: 'stunSpore', level: 16 }, { moveId: 'sleepPowder', level: 17 }],
  },
  weedle: {
    pokedexId: 13,
    speciesName: '独角虫',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 40, atk: 35, def: 30, spa: 20, spd: 20, spe: 50 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',
    learnset: [{ moveId: 'poisonSting', level: 1 }, { moveId: 'stringShot', level: 1 }],
    evolutions: [{ targetSpeciesId: 'kakuna', level: 7 }],
  },
  kakuna: {
    pokedexId: 14,
    speciesName: '铁壳蛹',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 45, atk: 25, def: 50, spa: 25, spd: 25, spe: 35 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',
    learnset: [{ moveId: 'harden', level: 1 }],
    evolutions: [{ targetSpeciesId: 'beedrill', level: 10 }],
  },
  beedrill: {
    pokedexId: 15,
    speciesName: '大针蜂',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 65, atk: 90, def: 40, spa: 45, spd: 80, spe: 75 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',
    learnset: [{ moveId: 'furyAttack', level: 1 }, { moveId: 'focusEnergy', level: 16 }, { moveId: 'twineedle', level: 20 }, { moveId: 'rage', level: 25 }],
  },
  pidgey: {
    pokedexId: 16,
    speciesName: '波波',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 40, atk: 45, def: 40, spa: 35, spd: 35, spe: 56 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',
    learnset: [{ moveId: 'gust', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'sandAttack', level: 5 }, { moveId: 'quickAttack', level: 12 }],
    evolutions: [{ targetSpeciesId: 'pidgeotto', level: 18 }],
  },
  pidgeotto: {
    pokedexId: 17,
    speciesName: '比比鸟',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 63, atk: 60, def: 55, spa: 50, spd: 50, spe: 71 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',
    learnset: [{ moveId: 'gust', level: 1 }, { moveId: 'sandAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'quickAttack', level: 12 }],
    evolutions: [{ targetSpeciesId: 'pidgeot', level: 36 }],
  },
  pidgeot: {
    pokedexId: 18,
    speciesName: '大比鸟',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 83, atk: 80, def: 75, spa: 70, spd: 70, spe: 101 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',
    learnset: [{ moveId: 'gust', level: 1 }, { moveId: 'sandAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'quickAttack', level: 1 }],
  },
  rattata: {
    pokedexId: 19,
    speciesName: '小拉达',
    types: ['Normal'],
    baseStats: { hp: 30, atk: 56, def: 35, spa: 25, spd: 35, spe: 72 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'quickAttack', level: 7 }, { moveId: 'hyperFang', level: 14 }],
    evolutions: [{ targetSpeciesId: 'raticate', level: 20 }],
  },
  raticate: {
    pokedexId: 20,
    speciesName: '拉达',
    types: ['Normal'],
    baseStats: { hp: 55, atk: 81, def: 60, spa: 50, spd: 70, spe: 97 },
    catchRate: 127,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'quickAttack', level: 1 }, { moveId: 'hyperFang', level: 14 }],
  },
  spearow: {
    pokedexId: 21,
    speciesName: '烈雀',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 40, atk: 60, def: 30, spa: 31, spd: 31, spe: 70 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',
    learnset: [{ moveId: 'growl', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'leer', level: 9 }, { moveId: 'furyAttack', level: 15 }],
    evolutions: [{ targetSpeciesId: 'fearow', level: 20 }],
  },
  fearow: {
    pokedexId: 22,
    speciesName: '大嘴雀',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 65, atk: 90, def: 65, spa: 61, spd: 61, spe: 100 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',
    learnset: [{ moveId: 'leer', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'furyAttack', level: 15 }],
  },
  ekans: {
    pokedexId: 23,
    speciesName: '阿柏蛇',
    types: ['Poison'],
    baseStats: { hp: 35, atk: 60, def: 44, spa: 40, spd: 54, spe: 55 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',
    learnset: [{ moveId: 'wrap', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'poisonSting', level: 10 }, { moveId: 'bite', level: 17 }],
    evolutions: [{ targetSpeciesId: 'arbok', level: 22 }],
  },
  arbok: {
    pokedexId: 24,
    speciesName: '阿柏怪',
    types: ['Poison'],
    baseStats: { hp: 60, atk: 95, def: 69, spa: 65, spd: 79, spe: 80 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png',
    learnset: [{ moveId: 'wrap', level: 1 }, { moveId: 'poisonSting', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'bite', level: 17 }],
  },
  pikachu: {
    pokedexId: 25,
    speciesName: '皮卡丘',
    types: ['Electric'],
    baseStats: { hp: 35, atk: 55, def: 40, spa: 50, spd: 50, spe: 90 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    learnset: [{ moveId: 'growl', level: 1 }, { moveId: 'thunderShock', level: 1 }, { moveId: 'tailWhip', level: 6 }, { moveId: 'thunderWave', level: 9 }],
    evolutions: [{ targetSpeciesId: 'raichu', item: 'thunder-stone' }],
  },
  raichu: {
    pokedexId: 26,
    speciesName: '雷丘',
    types: ['Electric'],
    baseStats: { hp: 60, atk: 90, def: 55, spa: 90, spd: 80, spe: 110 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',
    learnset: [{ moveId: 'tailWhip', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'thunderShock', level: 1 }, { moveId: 'thunderbolt', level: 1 }],
  },
  sandshrew: {
    pokedexId: 27,
    speciesName: '穿山鼠',
    types: ['Ground'],
    baseStats: { hp: 50, atk: 75, def: 85, spa: 20, spd: 30, spe: 40 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'defenseCurl', level: 6 }, { moveId: 'sandAttack', level: 10 }, { moveId: 'slash', level: 17 }],
    evolutions: [{ targetSpeciesId: 'sandslash', level: 22 }],
  },
  sandslash: {
    pokedexId: 28,
    speciesName: '穿山王',
    types: ['Ground'],
    baseStats: { hp: 75, atk: 100, def: 110, spa: 45, spd: 55, spe: 65 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'sandAttack', level: 1 }, { moveId: 'defenseCurl', level: 1 }, { moveId: 'slash', level: 17 }],
  },
  'nidoran-f': {
    pokedexId: 29,
    speciesName: '尼多兰',
    types: ['Poison'],
    baseStats: { hp: 55, atk: 47, def: 52, spa: 40, spd: 40, spe: 41 },
    catchRate: 235,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'scratch', level: 8 }, { moveId: 'poisonSting', level: 14 }],
    evolutions: [{ targetSpeciesId: 'nidorina', level: 16 }],
  },
  nidorina: {
    pokedexId: 30,
    speciesName: '尼多娜',
    types: ['Poison'],
    baseStats: { hp: 70, atk: 62, def: 67, spa: 55, spd: 55, spe: 56 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'poisonSting', level: 14 }],
    evolutions: [{ targetSpeciesId: 'nidoqueen', item: 'moon-stone' }],
  },
  nidoqueen: {
    pokedexId: 31,
    speciesName: '尼多后',
    types: ['Poison', 'Ground'],
    baseStats: { hp: 90, atk: 92, def: 87, spa: 75, spd: 85, spe: 76 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'bodySlam', level: 1 }, { moveId: 'tailWhip', level: 1 }],
  },
  'nidoran-m': {
    pokedexId: 32,
    speciesName: '尼多朗',
    types: ['Poison'],
    baseStats: { hp: 46, atk: 57, def: 40, spa: 40, spd: 40, spe: 50 },
    catchRate: 235,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'hornAttack', level: 8 }],
    evolutions: [{ targetSpeciesId: 'nidorino', level: 16 }],
  },
  nidorino: {
    pokedexId: 33,
    speciesName: '尼多力诺',
    types: ['Poison'],
    baseStats: { hp: 61, atk: 72, def: 57, spa: 55, spd: 55, spe: 65 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png',
    learnset: [{ moveId: 'hornAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'peck', level: 1 }],
    evolutions: [{ targetSpeciesId: 'nidoking', item: 'moon-stone' }],
  },
  nidoking: {
    pokedexId: 34,
    speciesName: '尼多王',
    types: ['Poison', 'Ground'],
    baseStats: { hp: 81, atk: 102, def: 77, spa: 85, spd: 75, spe: 85 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png',
    learnset: [{ moveId: 'hornAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'thrash', level: 1 }, { moveId: 'poisonSting', level: 1 }],
  },
  clefairy: {
    pokedexId: 35,
    speciesName: '皮皮',
    types: ['Fairy'],
    baseStats: { hp: 70, atk: 45, def: 48, spa: 60, spd: 65, spe: 35 },
    catchRate: 150,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'encore', level: 5 }, { moveId: 'sing', level: 13 }],
    evolutions: [{ targetSpeciesId: 'clefable', item: 'moon-stone' }],
  },
  clefable: {
    pokedexId: 36,
    speciesName: '皮可西',
    types: ['Fairy'],
    baseStats: { hp: 95, atk: 70, def: 73, spa: 95, spd: 90, spe: 60 },
    catchRate: 25,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',
    learnset: [{ moveId: 'doubleSlap', level: 1 }, { moveId: 'sing', level: 1 }, { moveId: 'minimize', level: 1 }, { moveId: 'metronome', level: 1 }],
  },
  vulpix: {
    pokedexId: 37,
    speciesName: '六尾',
    types: ['Fire'],
    baseStats: { hp: 38, atk: 41, def: 40, spa: 50, spd: 65, spe: 65 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',
    learnset: [{ moveId: 'tailWhip', level: 1 }, { moveId: 'ember', level: 1 }, { moveId: 'quickAttack', level: 16 }, { moveId: 'willOWisp', level: 17 }],
    evolutions: [{ targetSpeciesId: 'ninetales', item: 'fire-stone' }],
  },
  ninetales: {
    pokedexId: 38,
    speciesName: '九尾',
    types: ['Fire'],
    baseStats: { hp: 73, atk: 76, def: 75, spa: 81, spd: 100, spe: 100 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',
    learnset: [{ moveId: 'tailWhip', level: 1 }, { moveId: 'roar', level: 1 }, { moveId: 'ember', level: 1 }, { moveId: 'quickAttack', level: 1 }],
  },
  jigglypuff: {
    pokedexId: 39,
    speciesName: '胖丁',
    types: ['Normal', 'Fairy'],
    baseStats: { hp: 115, atk: 45, def: 20, spa: 45, spd: 25, spe: 20 },
    catchRate: 170,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',
    learnset: [{ moveId: 'sing', level: 1 }, { moveId: 'pound', level: 9 }, { moveId: 'disable', level: 14 }, { moveId: 'defenseCurl', level: 19 }],
    evolutions: [{ targetSpeciesId: 'wigglytuff', item: 'moon-stone' }],
  },
  wigglytuff: {
    pokedexId: 40,
    speciesName: '胖可丁',
    types: ['Normal', 'Fairy'],
    baseStats: { hp: 140, atk: 70, def: 45, spa: 85, spd: 50, spe: 45 },
    catchRate: 50,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',
    learnset: [{ moveId: 'doubleSlap', level: 1 }, { moveId: 'sing', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'defenseCurl', level: 1 }],
  },
  zubat: {
    pokedexId: 41,
    speciesName: '超音蝠',
    types: ['Poison', 'Flying'],
    baseStats: { hp: 40, atk: 45, def: 35, spa: 30, spd: 40, spe: 55 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',
    learnset: [{ moveId: 'leechLife', level: 1 }, { moveId: 'astonish', level: 6 }, { moveId: 'supersonic', level: 10 }, { moveId: 'bite', level: 15 }],
    evolutions: [{ targetSpeciesId: 'golbat', level: 22 }],
  },
  golbat: {
    pokedexId: 42,
    speciesName: '大嘴蝠',
    types: ['Poison', 'Flying'],
    baseStats: { hp: 75, atk: 80, def: 70, spa: 65, spd: 75, spe: 90 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',
    learnset: [{ moveId: 'bite', level: 1 }, { moveId: 'screech', level: 1 }, { moveId: 'leechLife', level: 1 }, { moveId: 'astonish', level: 1 }],
  },
  oddish: {
    pokedexId: 43,
    speciesName: '走路草',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 45, atk: 50, def: 55, spa: 75, spd: 65, spe: 30 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',
    learnset: [{ moveId: 'absorb', level: 1 }, { moveId: 'sweetScent', level: 7 }, { moveId: 'poisonPowder', level: 15 }, { moveId: 'stunSpore', level: 17 }, { moveId: 'sunnyDay', level: 22 }],
    evolutions: [{ targetSpeciesId: 'gloom', level: 21 }],
  },
  gloom: {
    pokedexId: 44,
    speciesName: '臭臭花',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 60, atk: 65, def: 70, spa: 85, spd: 75, spe: 40 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',
    learnset: [{ moveId: 'absorb', level: 1 }, { moveId: 'poisonPowder', level: 1 }, { moveId: 'stunSpore', level: 1 }, { moveId: 'sweetScent', level: 1 }],
    evolutions: [{ targetSpeciesId: 'vileplume', item: 'leaf-stone' }],
  },
  vileplume: {
    pokedexId: 45,
    speciesName: '霸王花',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 75, atk: 80, def: 85, spa: 110, spd: 90, spe: 50 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',
    learnset: [{ moveId: 'acid', level: 1 }, { moveId: 'absorb', level: 1 }, { moveId: 'megaDrain', level: 1 }, { moveId: 'stunSpore', level: 1 }],
  },
  paras: {
    pokedexId: 46,
    speciesName: '派拉斯',
    types: ['Bug', 'Grass'],
    baseStats: { hp: 35, atk: 70, def: 55, spa: 45, spd: 55, spe: 25 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'poisonPowder', level: 13 }, { moveId: 'stunSpore', level: 13 }, { moveId: 'leechLife', level: 20 }],
    evolutions: [{ targetSpeciesId: 'parasect', level: 24 }],
  },
  parasect: {
    pokedexId: 47,
    speciesName: '派拉斯特',
    types: ['Bug', 'Grass'],
    baseStats: { hp: 60, atk: 95, def: 80, spa: 60, spd: 80, spe: 30 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'poisonPowder', level: 1 }, { moveId: 'stunSpore', level: 1 }, { moveId: 'leechLife', level: 1 }],
  },
  venonat: {
    pokedexId: 48,
    speciesName: '毛球',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 60, atk: 55, def: 50, spa: 40, spd: 55, spe: 45 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'foresight', level: 1 }, { moveId: 'supersonic', level: 11 }],
    evolutions: [{ targetSpeciesId: 'venomoth', level: 31 }],
  },
  venomoth: {
    pokedexId: 49,
    speciesName: '摩鲁蛾',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 70, atk: 65, def: 60, spa: 90, spd: 75, spe: 90 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'supersonic', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'poisonPowder', level: 1 }],
  },
  diglett: {
    pokedexId: 50,
    speciesName: '地鼠',
    types: ['Ground'],
    baseStats: { hp: 10, atk: 55, def: 25, spa: 35, spd: 45, spe: 95 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'magnitude', level: 9 }, { moveId: 'growl', level: 15 }, { moveId: 'dig', level: 19 }],
    evolutions: [{ targetSpeciesId: 'dugtrio', level: 26 }],
  },
  dugtrio: {
    pokedexId: 51,
    speciesName: '三地鼠',
    types: ['Ground'],
    baseStats: { hp: 35, atk: 100, def: 50, spa: 50, spd: 70, spe: 120 },
    catchRate: 50,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'dig', level: 1 }, { moveId: 'triAttack', level: 1 }],
  },
  meowth: {
    pokedexId: 52,
    speciesName: '喵喵',
    types: ['Normal'],
    baseStats: { hp: 40, atk: 45, def: 35, spa: 40, spd: 40, spe: 90 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'bite', level: 12 }, { moveId: 'payDay', level: 17 }],
    evolutions: [{ targetSpeciesId: 'persian', level: 28 }],
  },
  persian: {
    pokedexId: 53,
    speciesName: '猫老大',
    types: ['Normal'],
    baseStats: { hp: 65, atk: 70, def: 60, spa: 65, spd: 65, spe: 115 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'bite', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'screech', level: 1 }],
  },
  psyduck: {
    pokedexId: 54,
    speciesName: '可达鸭',
    types: ['Water'],
    baseStats: { hp: 50, atk: 52, def: 48, spa: 65, spd: 50, spe: 55 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'waterSport', level: 1 }, { moveId: 'screech', level: 23 }, { moveId: 'tailWhip', level: 28 }, { moveId: 'rainDance', level: 32 }],
    evolutions: [{ targetSpeciesId: 'golduck', level: 33 }],
  },
  golduck: {
    pokedexId: 55,
    speciesName: '哥达鸭',
    types: ['Water'],
    baseStats: { hp: 80, atk: 82, def: 78, spa: 95, spd: 80, spe: 85 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'waterSport', level: 1 }],
  },
  mankey: {
    pokedexId: 56,
    speciesName: '猴怪',
    types: ['Fighting'],
    baseStats: { hp: 40, atk: 80, def: 35, spa: 35, spd: 45, spe: 70 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'lowKick', level: 9 }, { moveId: 'karateChop', level: 15 }],
    evolutions: [{ targetSpeciesId: 'primeape', level: 28 }],
  },
  primeape: {
    pokedexId: 57,
    speciesName: '火暴猴',
    types: ['Fighting'],
    baseStats: { hp: 65, atk: 105, def: 60, spa: 60, spd: 70, spe: 95 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png',
    learnset: [{ moveId: 'karateChop', level: 1 }, { moveId: 'scratch', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'lowKick', level: 1 }],
  },
  growlithe: {
    pokedexId: 58,
    speciesName: '卡蒂狗',
    types: ['Fire'],
    baseStats: { hp: 55, atk: 70, def: 45, spa: 70, spd: 50, spe: 60 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png',
    learnset: [{ moveId: 'bite', level: 1 }, { moveId: 'roar', level: 1 }, { moveId: 'ember', level: 18 }, { moveId: 'odorSleuth', level: 19 }],
    evolutions: [{ targetSpeciesId: 'arcanine', item: 'fire-stone' }],
  },
  arcanine: {
    pokedexId: 59,
    speciesName: '风速狗',
    types: ['Fire'],
    baseStats: { hp: 90, atk: 110, def: 80, spa: 100, spd: 80, spe: 95 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png',
    learnset: [{ moveId: 'takeDown', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'bite', level: 1 }, { moveId: 'roar', level: 1 }],
  },
  poliwag: {
    pokedexId: 60,
    speciesName: '蚊香蝌蚪',
    types: ['Water'],
    baseStats: { hp: 40, atk: 50, def: 40, spa: 40, spd: 40, spe: 90 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png',
    learnset: [{ moveId: 'bubble', level: 1 }, { moveId: 'hypnosis', level: 16 }, { moveId: 'waterGun', level: 19 }, { moveId: 'doubleSlap', level: 25 }, { moveId: 'rainDance', level: 28 }],
    evolutions: [{ targetSpeciesId: 'poliwhirl', level: 25 }],
  },
  poliwhirl: {
    pokedexId: 61,
    speciesName: '蚊香君',
    types: ['Water'],
    baseStats: { hp: 65, atk: 65, def: 65, spa: 50, spd: 50, spe: 90 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png',
    learnset: [{ moveId: 'waterGun', level: 1 }, { moveId: 'hypnosis', level: 1 }, { moveId: 'bubble', level: 1 }, { moveId: 'doubleSlap', level: 26 }],
    evolutions: [{ targetSpeciesId: 'poliwrath', item: 'water-stone' }],
  },
  poliwrath: {
    pokedexId: 62,
    speciesName: '蚊香泳士',
    types: ['Water', 'Fighting'],
    baseStats: { hp: 90, atk: 95, def: 95, spa: 70, spd: 90, spe: 70 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png',
    learnset: [{ moveId: 'doubleSlap', level: 1 }, { moveId: 'bodySlam', level: 1 }, { moveId: 'waterGun', level: 1 }, { moveId: 'submission', level: 1 }],
  },
  abra: {
    pokedexId: 63,
    speciesName: '凯西',
    types: ['Psychic'],
    baseStats: { hp: 25, atk: 20, def: 15, spa: 105, spd: 55, spe: 90 },
    catchRate: 200,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png',
    learnset: [{ moveId: 'teleport', level: 1 }],
    evolutions: [{ targetSpeciesId: 'kadabra', level: 16 }],
  },
  kadabra: {
    pokedexId: 64,
    speciesName: '勇基拉',
    types: ['Psychic'],
    baseStats: { hp: 40, atk: 35, def: 30, spa: 120, spd: 70, spe: 105 },
    catchRate: 100,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png',
    learnset: [{ moveId: 'disable', level: 1 }, { moveId: 'confusion', level: 1 }, { moveId: 'teleport', level: 1 }, { moveId: 'kinesis', level: 1 }],
  },
  alakazam: {
    pokedexId: 65,
    speciesName: '胡地',
    types: ['Psychic'],
    baseStats: { hp: 55, atk: 50, def: 45, spa: 135, spd: 95, spe: 120 },
    catchRate: 50,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png',
    learnset: [{ moveId: 'disable', level: 1 }, { moveId: 'confusion', level: 1 }, { moveId: 'teleport', level: 1 }, { moveId: 'kinesis', level: 1 }],
  },
  machop: {
    pokedexId: 66,
    speciesName: '腕力',
    types: ['Fighting'],
    baseStats: { hp: 70, atk: 80, def: 50, spa: 35, spd: 35, spe: 35 },
    catchRate: 180,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png',
    learnset: [{ moveId: 'karateChop', level: 1 }, { moveId: 'lowKick', level: 20 }, { moveId: 'foresight', level: 22 }, { moveId: 'leer', level: 25 }],
    evolutions: [{ targetSpeciesId: 'machoke', level: 28 }],
  },
  machoke: {
    pokedexId: 67,
    speciesName: '豪力',
    types: ['Fighting'],
    baseStats: { hp: 80, atk: 100, def: 70, spa: 50, spd: 60, spe: 45 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png',
    learnset: [{ moveId: 'karateChop', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'lowKick', level: 1 }, { moveId: 'foresight', level: 22 }],
  },
  machamp: {
    pokedexId: 68,
    speciesName: '怪力',
    types: ['Fighting'],
    baseStats: { hp: 90, atk: 130, def: 80, spa: 65, spd: 85, spe: 55 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png',
    learnset: [{ moveId: 'karateChop', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'lowKick', level: 1 }, { moveId: 'foresight', level: 22 }],
  },
  bellsprout: {
    pokedexId: 69,
    speciesName: '喇叭芽',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 50, atk: 75, def: 35, spa: 70, spd: 30, spe: 40 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png',
    learnset: [{ moveId: 'vineWhip', level: 1 }, { moveId: 'growth', level: 1 }, { moveId: 'wrap', level: 13 }, { moveId: 'poisonPowder', level: 15 }],
    evolutions: [{ targetSpeciesId: 'weepinbell', level: 21 }],
  },
  weepinbell: {
    pokedexId: 70,
    speciesName: '口呆花',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 65, atk: 90, def: 50, spa: 85, spd: 45, spe: 55 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png',
    learnset: [{ moveId: 'vineWhip', level: 1 }, { moveId: 'wrap', level: 1 }, { moveId: 'growth', level: 1 }, { moveId: 'poisonPowder', level: 15 }],
    evolutions: [{ targetSpeciesId: 'victreebel', item: 'leaf-stone' }],
  },
  victreebel: {
    pokedexId: 71,
    speciesName: '大食花',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 80, atk: 105, def: 65, spa: 100, spd: 70, spe: 70 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png',
    learnset: [{ moveId: 'vineWhip', level: 1 }, { moveId: 'acid', level: 1 }, { moveId: 'razorLeaf', level: 1 }, { moveId: 'stunSpore', level: 1 }],
  },
  tentacool: {
    pokedexId: 72,
    speciesName: '玛瑙水母',
    types: ['Water', 'Poison'],
    baseStats: { hp: 40, atk: 40, def: 35, spa: 50, spd: 100, spe: 70 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png',
    learnset: [{ moveId: 'acid', level: 1 }, { moveId: 'supersonic', level: 7 }, { moveId: 'wrap', level: 13 }, { moveId: 'poisonSting', level: 18 }],
    evolutions: [{ targetSpeciesId: 'tentacruel', level: 30 }],
  },
  tentacruel: {
    pokedexId: 73,
    speciesName: '毒刺水母',
    types: ['Water', 'Poison'],
    baseStats: { hp: 80, atk: 70, def: 65, spa: 80, spd: 120, spe: 100 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png',
    learnset: [{ moveId: 'wrap', level: 1 }, { moveId: 'supersonic', level: 1 }, { moveId: 'acid', level: 1 }, { moveId: 'poisonSting', level: 18 }],
  },
  geodude: {
    pokedexId: 74,
    speciesName: '小拳石',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 40, atk: 80, def: 100, spa: 30, spd: 30, spe: 20 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'mudSport', level: 6 }, { moveId: 'defenseCurl', level: 11 }, { moveId: 'rockThrow', level: 16 }, { moveId: 'sandstorm', level: 22 }],
    evolutions: [{ targetSpeciesId: 'graveler', level: 25 }],
  },
  graveler: {
    pokedexId: 75,
    speciesName: '隆隆石',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 55, atk: 95, def: 115, spa: 45, spd: 45, spe: 35 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'defenseCurl', level: 1 }, { moveId: 'mudSport', level: 1 }, { moveId: 'rockThrow', level: 16 }],
  },
  golem: {
    pokedexId: 76,
    speciesName: '隆隆岩',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 80, atk: 120, def: 130, spa: 55, spd: 65, spe: 45 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'defenseCurl', level: 1 }, { moveId: 'mudSport', level: 1 }, { moveId: 'rockThrow', level: 16 }],
  },
  ponyta: {
    pokedexId: 77,
    speciesName: '小火马',
    types: ['Fire'],
    baseStats: { hp: 50, atk: 85, def: 55, spa: 65, spd: 65, spe: 90 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png',
    learnset: [{ moveId: 'ember', level: 1 }, { moveId: 'quickAttack', level: 1 }, { moveId: 'tailWhip', level: 30 }, { moveId: 'stomp', level: 32 }],
    evolutions: [{ targetSpeciesId: 'rapidash', level: 40 }],
  },
  rapidash: {
    pokedexId: 78,
    speciesName: '烈焰马',
    types: ['Fire'],
    baseStats: { hp: 65, atk: 100, def: 70, spa: 80, spd: 80, spe: 105 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png',
    learnset: [{ moveId: 'stomp', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'ember', level: 1 }],
  },
  slowpoke: {
    pokedexId: 79,
    speciesName: '呆呆兽',
    types: ['Water', 'Psychic'],
    baseStats: { hp: 90, atk: 65, def: 65, spa: 40, spd: 40, spe: 15 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'confusion', level: 1 }, { moveId: 'curse', level: 1 }, { moveId: 'yawn', level: 1 }],
    evolutions: [{ targetSpeciesId: 'slowbro', level: 37 }],
  },
  slowbro: {
    pokedexId: 80,
    speciesName: '呆壳兽',
    types: ['Water', 'Psychic'],
    baseStats: { hp: 95, atk: 75, def: 110, spa: 100, spd: 80, spe: 30 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png',
    learnset: [{ moveId: 'headbutt', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'confusion', level: 1 }],
  },
  magnemite: {
    pokedexId: 81,
    speciesName: '小磁怪',
    types: ['Electric', 'Steel'],
    baseStats: { hp: 25, atk: 35, def: 70, spa: 95, spd: 55, spe: 45 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'metalSound', level: 1 }, { moveId: 'sonicBoom', level: 21 }, { moveId: 'thunderShock', level: 25 }],
    evolutions: [{ targetSpeciesId: 'magneton', level: 30 }],
  },
  magneton: {
    pokedexId: 82,
    speciesName: '三合一磁怪',
    types: ['Electric', 'Steel'],
    baseStats: { hp: 50, atk: 60, def: 95, spa: 120, spd: 70, spe: 70 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'sonicBoom', level: 1 }, { moveId: 'thunderShock', level: 1 }, { moveId: 'metalSound', level: 1 }],
  },
  farfetchd: {
    pokedexId: 83,
    speciesName: '大葱鸭',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 52, atk: 90, def: 55, spa: 58, spd: 62, spe: 60 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png',
    learnset: [{ moveId: 'sandAttack', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'leer', level: 7 }, { moveId: 'furyAttack', level: 15 }],
  },
  doduo: {
    pokedexId: 84,
    speciesName: '嘟嘟',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 35, atk: 85, def: 45, spa: 35, spd: 35, spe: 75 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png',
    learnset: [{ moveId: 'peck', level: 1 }, { moveId: 'pursuit', level: 9 }, { moveId: 'growl', level: 20 }, { moveId: 'furyAttack', level: 24 }],
    evolutions: [{ targetSpeciesId: 'dodrio', level: 31 }],
  },
  dodrio: {
    pokedexId: 85,
    speciesName: '嘟嘟利',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 60, atk: 110, def: 70, spa: 60, spd: 60, spe: 110 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png',
    learnset: [{ moveId: 'furyAttack', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'pursuit', level: 1 }],
  },
  seel: {
    pokedexId: 86,
    speciesName: '小海狮',
    types: ['Water'],
    baseStats: { hp: 65, atk: 45, def: 55, spa: 45, spd: 70, spe: 45 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png',
    learnset: [{ moveId: 'headbutt', level: 1 }, { moveId: 'icyWind', level: 17 }, { moveId: 'growl', level: 30 }, { moveId: 'auroraBeam', level: 35 }, { moveId: 'hail', level: 40 }],
    evolutions: [{ targetSpeciesId: 'dewgong', level: 34 }],
  },
  dewgong: {
    pokedexId: 87,
    speciesName: '白海狮',
    types: ['Water', 'Ice'],
    baseStats: { hp: 90, atk: 70, def: 80, spa: 70, spd: 95, spe: 70 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png',
    learnset: [{ moveId: 'headbutt', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'auroraBeam', level: 1 }, { moveId: 'icyWind', level: 1 }],
  },
  grimer: {
    pokedexId: 88,
    speciesName: '臭泥',
    types: ['Poison'],
    baseStats: { hp: 80, atk: 80, def: 50, spa: 40, spd: 50, spe: 25 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'poisonGas', level: 30 }, { moveId: 'minimize', level: 33 }],
    evolutions: [{ targetSpeciesId: 'muk', level: 38 }],
  },
  muk: {
    pokedexId: 89,
    speciesName: '臭臭泥',
    types: ['Poison'],
    baseStats: { hp: 105, atk: 105, def: 75, spa: 65, spd: 100, spe: 50 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'poisonGas', level: 1 }, { moveId: 'minimize', level: 33 }],
  },
  shellder: {
    pokedexId: 90,
    speciesName: '大舌贝',
    types: ['Water'],
    baseStats: { hp: 30, atk: 65, def: 100, spa: 45, spd: 25, spe: 40 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'withdraw', level: 1 }, { moveId: 'icicleSpear', level: 8 }, { moveId: 'supersonic', level: 18 }],
    evolutions: [{ targetSpeciesId: 'cloyster', item: 'water-stone' }],
  },
  cloyster: {
    pokedexId: 91,
    speciesName: '刺甲贝',
    types: ['Water', 'Ice'],
    baseStats: { hp: 50, atk: 95, def: 180, spa: 85, spd: 45, spe: 70 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png',
    learnset: [{ moveId: 'supersonic', level: 1 }, { moveId: 'auroraBeam', level: 1 }, { moveId: 'withdraw', level: 1 }, { moveId: 'clamp', level: 1 }],
  },
  gastly: {
    pokedexId: 92,
    speciesName: '鬼斯',
    types: ['Ghost', 'Poison'],
    baseStats: { hp: 30, atk: 35, def: 30, spa: 100, spd: 35, spe: 80 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
    learnset: [{ moveId: 'nightShade', level: 1 }, { moveId: 'confuseRay', level: 1 }, { moveId: 'lick', level: 1 }, { moveId: 'spite', level: 8 }],
    evolutions: [{ targetSpeciesId: 'haunter', level: 25 }],
  },
  haunter: {
    pokedexId: 93,
    speciesName: '鬼斯通',
    types: ['Ghost', 'Poison'],
    baseStats: { hp: 45, atk: 50, def: 45, spa: 115, spd: 55, spe: 95 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png',
    learnset: [{ moveId: 'nightShade', level: 1 }, { moveId: 'confuseRay', level: 1 }, { moveId: 'lick', level: 1 }, { moveId: 'spite', level: 1 }],
  },
  gengar: {
    pokedexId: 94,
    speciesName: '耿鬼',
    types: ['Ghost', 'Poison'],
    baseStats: { hp: 60, atk: 65, def: 60, spa: 130, spd: 75, spe: 110 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
    learnset: [{ moveId: 'nightShade', level: 1 }, { moveId: 'confuseRay', level: 1 }, { moveId: 'lick', level: 1 }, { moveId: 'spite', level: 1 }],
  },
  onix: {
    pokedexId: 95,
    speciesName: '大岩蛇',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 35, atk: 45, def: 160, spa: 30, spd: 45, spe: 70 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'screech', level: 1 }, { moveId: 'bind', level: 15 }, { moveId: 'rockThrow', level: 19 }, { moveId: 'sandstorm', level: 25 }],
  },
  drowzee: {
    pokedexId: 96,
    speciesName: '催眠貘',
    types: ['Psychic'],
    baseStats: { hp: 60, atk: 48, def: 45, spa: 43, spd: 90, spe: 42 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'hypnosis', level: 1 }, { moveId: 'disable', level: 12 }, { moveId: 'confusion', level: 17 }],
    evolutions: [{ targetSpeciesId: 'hypno', level: 26 }],
  },
  hypno: {
    pokedexId: 97,
    speciesName: '引梦貘人',
    types: ['Psychic'],
    baseStats: { hp: 85, atk: 73, def: 70, spa: 73, spd: 115, spe: 67 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'disable', level: 1 }, { moveId: 'confusion', level: 1 }, { moveId: 'hypnosis', level: 1 }],
  },
  krabby: {
    pokedexId: 98,
    speciesName: '大钳蟹',
    types: ['Water'],
    baseStats: { hp: 30, atk: 105, def: 90, spa: 25, spd: 25, spe: 50 },
    catchRate: 225,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png',
    learnset: [{ moveId: 'leer', level: 1 }, { moveId: 'bubble', level: 1 }, { moveId: 'viceGrip', level: 20 }, { moveId: 'mudShot', level: 23 }],
    evolutions: [{ targetSpeciesId: 'kingler', level: 28 }],
  },
  kingler: {
    pokedexId: 99,
    speciesName: '巨钳蟹',
    types: ['Water'],
    baseStats: { hp: 55, atk: 130, def: 115, spa: 50, spd: 50, spe: 75 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png',
    learnset: [{ moveId: 'viceGrip', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'bubble', level: 1 }, { moveId: 'metalClaw', level: 1 }],
  },
  voltorb: {
    pokedexId: 100,
    speciesName: '霹雳电球',
    types: ['Electric'],
    baseStats: { hp: 40, atk: 30, def: 50, spa: 55, spd: 55, spe: 100 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'screech', level: 1 }, { moveId: 'charge', level: 1 }, { moveId: 'sonicBoom', level: 17 }],
    evolutions: [{ targetSpeciesId: 'electrode', level: 30 }],
  },
  electrode: {
    pokedexId: 101,
    speciesName: '顽皮雷弹',
    types: ['Electric'],
    baseStats: { hp: 60, atk: 50, def: 70, spa: 80, spd: 80, spe: 150 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'sonicBoom', level: 1 }, { moveId: 'screech', level: 1 }, { moveId: 'charge', level: 1 }],
  },
  exeggcute: {
    pokedexId: 102,
    speciesName: '蛋蛋',
    types: ['Grass', 'Psychic'],
    baseStats: { hp: 60, atk: 40, def: 80, spa: 60, spd: 45, spe: 40 },
    catchRate: 90,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png',
    learnset: [{ moveId: 'hypnosis', level: 1 }, { moveId: 'barrage', level: 1 }, { moveId: 'uproar', level: 1 }, { moveId: 'confusion', level: 19 }],
    evolutions: [{ targetSpeciesId: 'exeggutor', item: 'leaf-stone' }],
  },
  exeggutor: {
    pokedexId: 103,
    speciesName: '椰蛋树',
    types: ['Grass', 'Psychic'],
    baseStats: { hp: 95, atk: 95, def: 85, spa: 125, spd: 75, spe: 55 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png',
    learnset: [{ moveId: 'confusion', level: 1 }, { moveId: 'hypnosis', level: 1 }, { moveId: 'barrage', level: 1 }, { moveId: 'stomp', level: 28 }],
  },
  cubone: {
    pokedexId: 104,
    speciesName: '卡拉卡拉',
    types: ['Ground'],
    baseStats: { hp: 50, atk: 50, def: 95, spa: 40, spd: 50, spe: 35 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png',
    learnset: [{ moveId: 'growl', level: 1 }, { moveId: 'boneClub', level: 1 }, { moveId: 'tailWhip', level: 13 }, { moveId: 'headbutt', level: 18 }],
    evolutions: [{ targetSpeciesId: 'marowak', level: 28 }],
  },
  marowak: {
    pokedexId: 105,
    speciesName: '嘎啦嘎啦',
    types: ['Ground'],
    baseStats: { hp: 60, atk: 80, def: 110, spa: 50, spd: 80, spe: 45 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png',
    learnset: [{ moveId: 'tailWhip', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'growl', level: 1 }, { moveId: 'focusEnergy', level: 1 }],
  },
  hitmonlee: {
    pokedexId: 106,
    speciesName: '飞腿郎',
    types: ['Fighting'],
    baseStats: { hp: 50, atk: 120, def: 53, spa: 35, spd: 110, spe: 87 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png',
    learnset: [{ moveId: 'doubleKick', level: 1 }, { moveId: 'meditate', level: 1 }, { moveId: 'revenge', level: 1 }, { moveId: 'brickBreak', level: 20 }],
  },
  hitmonchan: {
    pokedexId: 107,
    speciesName: '快拳郎',
    types: ['Fighting'],
    baseStats: { hp: 50, atk: 105, def: 79, spa: 35, spd: 110, spe: 76 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png',
    learnset: [{ moveId: 'cometPunch', level: 1 }, { moveId: 'agility', level: 1 }, { moveId: 'revenge', level: 1 }, { moveId: 'pursuit', level: 13 }],
  },
  lickitung: {
    pokedexId: 108,
    speciesName: '大舌头',
    types: ['Normal'],
    baseStats: { hp: 90, atk: 55, def: 75, spa: 60, spd: 75, spe: 30 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png',
    learnset: [{ moveId: 'wrap', level: 1 }, { moveId: 'supersonic', level: 1 }, { moveId: 'lick', level: 1 }, { moveId: 'stomp', level: 7 }],
  },
  koffing: {
    pokedexId: 109,
    speciesName: '瓦斯弹',
    types: ['Poison'],
    baseStats: { hp: 40, atk: 65, def: 95, spa: 60, spd: 45, spe: 35 },
    catchRate: 190,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'smog', level: 1 }, { moveId: 'poisonGas', level: 1 }, { moveId: 'sludge', level: 32 }],
    evolutions: [{ targetSpeciesId: 'weezing', level: 35 }],
  },
  weezing: {
    pokedexId: 110,
    speciesName: '双弹瓦斯',
    types: ['Poison'],
    baseStats: { hp: 65, atk: 90, def: 120, spa: 85, spd: 70, spe: 60 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'smog', level: 1 }, { moveId: 'sludge', level: 1 }, { moveId: 'poisonGas', level: 1 }],
  },
  rhyhorn: {
    pokedexId: 111,
    speciesName: '独角犀牛',
    types: ['Ground', 'Rock'],
    baseStats: { hp: 80, atk: 85, def: 95, spa: 30, spd: 30, spe: 25 },
    catchRate: 120,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png',
    learnset: [{ moveId: 'hornAttack', level: 1 }, { moveId: 'scaryFace', level: 24 }, { moveId: 'rockBlast', level: 29 }, { moveId: 'stomp', level: 30 }],
    evolutions: [{ targetSpeciesId: 'rhydon', level: 42 }],
  },
  rhydon: {
    pokedexId: 112,
    speciesName: '钻角犀兽',
    types: ['Ground', 'Rock'],
    baseStats: { hp: 105, atk: 130, def: 120, spa: 45, spd: 45, spe: 40 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png',
    learnset: [{ moveId: 'stomp', level: 1 }, { moveId: 'hornAttack', level: 1 }, { moveId: 'furyAttack', level: 1 }, { moveId: 'tailWhip', level: 1 }],
  },
  chansey: {
    pokedexId: 113,
    speciesName: '吉利蛋',
    types: ['Normal'],
    baseStats: { hp: 250, atk: 5, def: 5, spa: 35, spd: 105, spe: 50 },
    catchRate: 30,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'doubleSlap', level: 1 }, { moveId: 'tailWhip', level: 1 }, { moveId: 'refresh', level: 9 }],
  },
  tangela: {
    pokedexId: 114,
    speciesName: '蔓藤怪',
    types: ['Grass'],
    baseStats: { hp: 65, atk: 55, def: 115, spa: 100, spd: 40, spe: 60 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png',
    learnset: [{ moveId: 'bind', level: 1 }, { moveId: 'constrict', level: 1 }, { moveId: 'ingrain', level: 1 }, { moveId: 'vineWhip', level: 29 }],
  },
  kangaskhan: {
    pokedexId: 115,
    speciesName: '袋兽',
    types: ['Normal'],
    baseStats: { hp: 105, atk: 95, def: 80, spa: 40, spd: 80, spe: 90 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png',
    learnset: [{ moveId: 'cometPunch', level: 1 }, { moveId: 'rage', level: 1 }, { moveId: 'fakeOut', level: 19 }, { moveId: 'bite', level: 26 }],
  },
  horsea: {
    pokedexId: 116,
    speciesName: '墨海马',
    types: ['Water'],
    baseStats: { hp: 30, atk: 40, def: 70, spa: 70, spd: 25, spe: 60 },
    catchRate: 225,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png',
    learnset: [{ moveId: 'bubble', level: 1 }, { moveId: 'smokescreen', level: 19 }, { moveId: 'leer', level: 24 }, { moveId: 'twister', level: 29 }],
    evolutions: [{ targetSpeciesId: 'seadra', level: 32 }],
  },
  seadra: {
    pokedexId: 117,
    speciesName: '海刺龙',
    types: ['Water'],
    baseStats: { hp: 55, atk: 65, def: 95, spa: 95, spd: 45, spe: 85 },
    catchRate: 75,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png',
    learnset: [{ moveId: 'smokescreen', level: 1 }, { moveId: 'bubble', level: 1 }, { moveId: 'leer', level: 24 }, { moveId: 'twister', level: 29 }],
  },
  goldeen: {
    pokedexId: 118,
    speciesName: '角金鱼',
    types: ['Water'],
    baseStats: { hp: 45, atk: 67, def: 60, spa: 35, spd: 50, spe: 63 },
    catchRate: 225,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png',
    learnset: [{ moveId: 'tailWhip', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'waterSport', level: 1 }, { moveId: 'supersonic', level: 19 }],
    evolutions: [{ targetSpeciesId: 'seaking', level: 33 }],
  },
  seaking: {
    pokedexId: 119,
    speciesName: '金鱼王',
    types: ['Water'],
    baseStats: { hp: 80, atk: 92, def: 65, spa: 65, spd: 80, spe: 68 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png',
    learnset: [{ moveId: 'tailWhip', level: 1 }, { moveId: 'supersonic', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'waterSport', level: 1 }],
  },
  staryu: {
    pokedexId: 120,
    speciesName: '海星星',
    types: ['Water'],
    baseStats: { hp: 30, atk: 45, def: 55, spa: 70, spd: 55, spe: 85 },
    catchRate: 225,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'rapidSpin', level: 10 }, { moveId: 'waterGun', level: 17 }, { moveId: 'camouflage', level: 19 }],
    evolutions: [{ targetSpeciesId: 'starmie', item: 'water-stone' }],
  },
  starmie: {
    pokedexId: 121,
    speciesName: '宝石海星',
    types: ['Water', 'Psychic'],
    baseStats: { hp: 60, atk: 75, def: 85, spa: 100, spd: 85, spe: 115 },
    catchRate: 60,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'waterGun', level: 1 }, { moveId: 'recover', level: 1 }, { moveId: 'harden', level: 1 }],
  },
  'mr-mime': {
    pokedexId: 122,
    speciesName: '魔墙人偶',
    types: ['Psychic', 'Fairy'],
    baseStats: { hp: 40, atk: 45, def: 65, spa: 100, spd: 120, spe: 90 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png',
    learnset: [{ moveId: 'confusion', level: 1 }, { moveId: 'barrier', level: 1 }, { moveId: 'reflect', level: 19 }, { moveId: 'magicalLeaf', level: 22 }],
  },
  scyther: {
    pokedexId: 123,
    speciesName: '飞天螳螂',
    types: ['Bug', 'Flying'],
    baseStats: { hp: 70, atk: 110, def: 80, spa: 55, spd: 80, spe: 105 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png',
    learnset: [{ moveId: 'quickAttack', level: 1 }, { moveId: 'pursuit', level: 11 }, { moveId: 'falseSwipe', level: 16 }, { moveId: 'leer', level: 17 }],
  },
  jynx: {
    pokedexId: 124,
    speciesName: '迷唇姐',
    types: ['Ice', 'Psychic'],
    baseStats: { hp: 65, atk: 50, def: 35, spa: 115, spd: 95, spe: 95 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'lovelyKiss', level: 1 }, { moveId: 'powderSnow', level: 1 }, { moveId: 'lick', level: 18 }],
  },
  electabuzz: {
    pokedexId: 125,
    speciesName: '电击兽',
    types: ['Electric'],
    baseStats: { hp: 65, atk: 83, def: 57, spa: 95, spd: 85, spe: 105 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png',
    learnset: [{ moveId: 'leer', level: 1 }, { moveId: 'quickAttack', level: 1 }, { moveId: 'swift', level: 25 }, { moveId: 'thunderShock', level: 34 }],
  },
  magmar: {
    pokedexId: 126,
    speciesName: '鸭嘴火兽',
    types: ['Fire'],
    baseStats: { hp: 65, atk: 95, def: 57, spa: 100, spd: 85, spe: 93 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png',
    learnset: [{ moveId: 'ember', level: 1 }, { moveId: 'sunnyDay', level: 33 }, { moveId: 'leer', level: 36 }, { moveId: 'confuseRay', level: 39 }],
  },
  pinsir: {
    pokedexId: 127,
    speciesName: '凯罗斯',
    types: ['Bug'],
    baseStats: { hp: 65, atk: 125, def: 100, spa: 55, spd: 70, spe: 85 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png',
    learnset: [{ moveId: 'viceGrip', level: 1 }, { moveId: 'bind', level: 21 }, { moveId: 'seismicToss', level: 25 }, { moveId: 'revenge', level: 25 }],
  },
  tauros: {
    pokedexId: 128,
    speciesName: '肯泰罗',
    types: ['Normal'],
    baseStats: { hp: 75, atk: 100, def: 95, spa: 40, spd: 70, spe: 110 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'hornAttack', level: 8 }, { moveId: 'scaryFace', level: 13 }, { moveId: 'pursuit', level: 19 }],
  },
  magikarp: {
    pokedexId: 129,
    speciesName: '鲤鱼王',
    types: ['Water'],
    baseStats: { hp: 20, atk: 10, def: 55, spa: 15, spd: 20, spe: 80 },
    catchRate: 255,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png',
    learnset: [{ moveId: 'splash', level: 1 }, { moveId: 'tackle', level: 15 }, { moveId: 'flail', level: 30 }],
    evolutions: [{ targetSpeciesId: 'gyarados', level: 20 }],
  },
  gyarados: {
    pokedexId: 130,
    speciesName: '暴鲤龙',
    types: ['Water', 'Flying'],
    baseStats: { hp: 95, atk: 125, def: 79, spa: 60, spd: 100, spe: 81 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'thrash', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'bite', level: 1 }],
  },
  lapras: {
    pokedexId: 131,
    speciesName: '拉普拉斯',
    types: ['Water', 'Ice'],
    baseStats: { hp: 130, atk: 85, def: 80, spa: 85, spd: 95, spe: 60 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png',
    learnset: [{ moveId: 'growl', level: 1 }, { moveId: 'waterGun', level: 1 }, { moveId: 'sing', level: 16 }, { moveId: 'mist', level: 20 }],
  },
  ditto: {
    pokedexId: 132,
    speciesName: '百变怪',
    types: ['Normal'],
    baseStats: { hp: 48, atk: 48, def: 48, spa: 48, spd: 48, spe: 48 },
    catchRate: 35,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png',
    learnset: [{ moveId: 'transform', level: 1 }],
  },
  eevee: {
    pokedexId: 133,
    speciesName: '伊布',
    types: ['Normal'],
    baseStats: { hp: 55, atk: 55, def: 50, spa: 45, spd: 65, spe: 55 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png',
    learnset: [{ moveId: 'sandAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'helpingHand', level: 1 }, { moveId: 'growl', level: 16 }],
    evolutions: [{ targetSpeciesId: 'flareon', item: 'fire-stone' }],
  },
  vaporeon: {
    pokedexId: 134,
    speciesName: '水伊布',
    types: ['Water'],
    baseStats: { hp: 130, atk: 65, def: 60, spa: 110, spd: 95, spe: 65 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png',
    learnset: [{ moveId: 'sandAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'waterGun', level: 1 }, { moveId: 'quickAttack', level: 1 }],
  },
  jolteon: {
    pokedexId: 135,
    speciesName: '雷伊布',
    types: ['Electric'],
    baseStats: { hp: 65, atk: 65, def: 60, spa: 110, spd: 95, spe: 130 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png',
    learnset: [{ moveId: 'sandAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'thunderShock', level: 1 }, { moveId: 'quickAttack', level: 1 }],
  },
  flareon: {
    pokedexId: 136,
    speciesName: '火伊布',
    types: ['Fire'],
    baseStats: { hp: 65, atk: 130, def: 60, spa: 95, spd: 110, spe: 65 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png',
    learnset: [{ moveId: 'sandAttack', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'ember', level: 1 }, { moveId: 'quickAttack', level: 1 }],
  },
  porygon: {
    pokedexId: 137,
    speciesName: '多边兽',
    types: ['Normal'],
    baseStats: { hp: 65, atk: 60, def: 70, spa: 85, spd: 75, spe: 40 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png',
    learnset: [{ moveId: 'tackle', level: 1 }, { moveId: 'sharpen', level: 1 }, { moveId: 'conversion', level: 1 }, { moveId: 'conversion2', level: 1 }],
  },
  omanyte: {
    pokedexId: 138,
    speciesName: '菊石兽',
    types: ['Rock', 'Water'],
    baseStats: { hp: 35, atk: 40, def: 100, spa: 90, spd: 55, spe: 35 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png',
    learnset: [{ moveId: 'waterGun', level: 1 }, { moveId: 'withdraw', level: 1 }, { moveId: 'constrict', level: 1 }, { moveId: 'bite', level: 13 }],
    evolutions: [{ targetSpeciesId: 'omastar', level: 40 }],
  },
  omastar: {
    pokedexId: 139,
    speciesName: '多刺菊石兽',
    types: ['Rock', 'Water'],
    baseStats: { hp: 70, atk: 60, def: 125, spa: 115, spd: 70, spe: 55 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png',
    learnset: [{ moveId: 'hornAttack', level: 1 }, { moveId: 'bite', level: 1 }, { moveId: 'waterGun', level: 1 }, { moveId: 'withdraw', level: 1 }],
  },
  kabuto: {
    pokedexId: 140,
    speciesName: '化石盔',
    types: ['Rock', 'Water'],
    baseStats: { hp: 30, atk: 80, def: 90, spa: 55, spd: 45, spe: 55 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'harden', level: 1 }, { moveId: 'mudShot', level: 25 }, { moveId: 'sandAttack', level: 31 }],
    evolutions: [{ targetSpeciesId: 'kabutops', level: 40 }],
  },
  kabutops: {
    pokedexId: 141,
    speciesName: '镰刀盔',
    types: ['Rock', 'Water'],
    baseStats: { hp: 60, atk: 115, def: 105, spa: 65, spd: 70, spe: 80 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png',
    learnset: [{ moveId: 'scratch', level: 1 }, { moveId: 'absorb', level: 1 }, { moveId: 'harden', level: 1 }, { moveId: 'furyCutter', level: 1 }],
  },
  aerodactyl: {
    pokedexId: 142,
    speciesName: '化石翼龙',
    types: ['Rock', 'Flying'],
    baseStats: { hp: 80, atk: 105, def: 65, spa: 60, spd: 75, spe: 130 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png',
    learnset: [{ moveId: 'wingAttack', level: 1 }, { moveId: 'agility', level: 1 }, { moveId: 'ancientPower', level: 29 }, { moveId: 'supersonic', level: 33 }],
  },
  snorlax: {
    pokedexId: 143,
    speciesName: '卡比兽',
    types: ['Normal'],
    baseStats: { hp: 160, atk: 110, def: 65, spa: 65, spd: 110, spe: 30 },
    catchRate: 25,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
    learnset: [{ moveId: 'headbutt', level: 1 }, { moveId: 'tackle', level: 1 }, { moveId: 'amnesia', level: 1 }, { moveId: 'rest', level: 1 }],
  },
  articuno: {
    pokedexId: 144,
    speciesName: '急冻鸟',
    types: ['Ice', 'Flying'],
    baseStats: { hp: 90, atk: 85, def: 100, spa: 95, spd: 125, spe: 85 },
    catchRate: 3,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png',
    learnset: [{ moveId: 'gust', level: 1 }, { moveId: 'iceBeam', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'powderSnow', level: 1 }],
  },
  zapdos: {
    pokedexId: 145,
    speciesName: '闪电鸟',
    types: ['Electric', 'Flying'],
    baseStats: { hp: 90, atk: 90, def: 85, spa: 125, spd: 90, spe: 100 },
    catchRate: 3,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png',
    learnset: [{ moveId: 'peck', level: 1 }, { moveId: 'drillPeck', level: 1 }, { moveId: 'thunderShock', level: 1 }, { moveId: 'thunderWave', level: 13 }],
  },
  moltres: {
    pokedexId: 146,
    speciesName: '火焰鸟',
    types: ['Fire', 'Flying'],
    baseStats: { hp: 90, atk: 100, def: 90, spa: 125, spd: 85, spe: 90 },
    catchRate: 3,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png',
    learnset: [{ moveId: 'wingAttack', level: 1 }, { moveId: 'ember', level: 1 }, { moveId: 'peck', level: 1 }, { moveId: 'fireSpin', level: 1 }],
  },
  dratini: {
    pokedexId: 147,
    speciesName: '迷你龙',
    types: ['Dragon'],
    baseStats: { hp: 41, atk: 64, def: 45, spa: 50, spd: 50, spe: 50 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png',
    learnset: [{ moveId: 'wrap', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'thunderWave', level: 10 }, { moveId: 'twister', level: 15 }],
    evolutions: [{ targetSpeciesId: 'dragonair', level: 30 }],
  },
  dragonair: {
    pokedexId: 148,
    speciesName: '哈克龙',
    types: ['Dragon'],
    baseStats: { hp: 61, atk: 84, def: 65, spa: 70, spd: 70, spe: 70 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png',
    learnset: [{ moveId: 'wrap', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'thunderWave', level: 1 }, { moveId: 'twister', level: 1 }],
    evolutions: [{ targetSpeciesId: 'dragonite', level: 55 }],
  },
  dragonite: {
    pokedexId: 149,
    speciesName: '快龙',
    types: ['Dragon', 'Flying'],
    baseStats: { hp: 91, atk: 134, def: 95, spa: 100, spd: 100, spe: 80 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png',
    learnset: [{ moveId: 'wrap', level: 1 }, { moveId: 'leer', level: 1 }, { moveId: 'thunderWave', level: 1 }, { moveId: 'agility', level: 1 }],
  },
  mewtwo: {
    pokedexId: 150,
    speciesName: '超梦',
    types: ['Psychic'],
    baseStats: { hp: 106, atk: 110, def: 90, spa: 154, spd: 90, spe: 130 },
    catchRate: 3,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
    learnset: [{ moveId: 'disable', level: 1 }, { moveId: 'confusion', level: 1 }, { moveId: 'psychic', level: 1 }, { moveId: 'swift', level: 1 }],
  },
  mew: {
    pokedexId: 151,
    speciesName: '梦幻',
    types: ['Psychic'],
    baseStats: { hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100 },
    catchRate: 45,
    spriteUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png',
    learnset: [{ moveId: 'pound', level: 1 }, { moveId: 'transform', level: 10 }, { moveId: 'megaPunch', level: 20 }, { moveId: 'metronome', level: 30 }],
  },
};

// 辅助函数
export const findSpeciesKeyByPokedexId = (pokedexId: number): string => {
  for (const [key, data] of Object.entries(SPECIES_DATA)) {
    if (data.pokedexId === pokedexId) {
      return key;
    }
  }
  return '';
};
