-- 在生产环境执行此脚本，解决迁移记录缺失问题
-- 执行前请确保数据库中有 User 和 GameSave 表

-- 插入迁移记录（如果不存在）
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, status)
VALUES (
    '20260125035536_init',
    '-- generated by prisma',
    NOW(),
    '20260125035536_init',
    NULL,
    NULL,
    NOW(),
    'applied'
)
ON CONFLICT (id) DO NOTHING;
